#' @description
#' Function to fit a `ranger` random forest model on an object `spatialsample`
#' split. Requires the packages `assertthat` (for input-checking), `rsample`
#' (for handling the data split object), `sf` (for removing spatial info
#' associated with the spatial sample), and `ranger` (for fitting hte random
#' forest).
#' 
#' @param data_split
#' Object generated by `spatialsample` package. Note that the object passed in
#' will still have `sf`-geometry associated with it. NOTE that current
#' implementation requires the DV in the ranger model to be `class` and all
#' other columns are included as IVs.
#' 
#' @param ranger_args
#' List or data frame with hyperparameters for `ranger` object. In current form,
#' requires `mtry`, `replace`, and `num.trees`.
#' 
#' @returns Prediction accuracy of fitted model on the provided testing dataset.

fit_ranger_on_split <- function(data_split, ranger_args) {
  
  # Making sure that inputs are formatted correctly
  # (there probably is a better way to do this... this can be saved for future versions)
  assertthat::assert_that('mtry' %in% names(ranger_args), msg = 'missing mtry')
  assertthat::assert_that('replace' %in% names(ranger_args), msg = 'missing replace')
  assertthat::assert_that('num.trees' %in% names(ranger_args), msg = 'missing num.trees')
  assertthat::assert_that('min.node.size' %in% names(ranger_args), msg = 'missing min.node.size')

  # Disaggregate data into testing and training datasets
  train_data <- rsample::analysis(data_split) |> sf::st_drop_geometry()
  test_data <- rsample::assessment(data_split) |> sf::st_drop_geometry()
  
  # Run ranger model with specified inputs
  mod <- ranger::ranger(
    formula = class ~ .,
    data = train_data,
    mtry = ranger_args$mtry,
    replace = ranger_args$replace,
    num.trees = ranger_args$num.trees,
    min.node.size = ranger_args$min.node.size,
    # Don't estimate error (this will speed things up)
    oob.error = FALSE
  )
  
  # Get prediction from random model 
  pred <- predict(mod, test_data)
  
  # Confusion matrix
  matr <- table(test_data$class, ranger::predictions(pred))
  
  # Return the accuracy of the model fit on this split
  pred_frac <- r_k_fun(matr)
 
  return(pred_frac)
   
}
